name = "OHDSIAPI"
uuid = "43fe992b-71c2-425c-b13e-efb1498069b1"
authors = ["Varshini Chinta <vchinta6@icl.gtri.org> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
